export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY'
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY'
export const LOAD_PRODUCT_DATA = 'LOAD_PRODUCT_DATA'
export const PRODUCT_LOADING = 'PRODUCT_LOADING'